<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [6]:
# Your code here
x = 5

assert x>=0, "No negative values! This is an all-natural supermarket!!!"

### 1.2 try-except

In [1]:

# Your code here
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.h
Oh oh! I cannot square h!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [8]:
# Yes, this is true
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

121

### 2.2 Docstrings

In [7]:
# if i'm being honest i will probably not remember to do this

def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [31]:
# this is very cool and very freeing

import numpy as np

def sentence_case(string):
    new = string.capitalize()
    
    if(len(string) > 1):
        new = new[0] + string[1:].lower()

    return new

def punctuate(string):
    return string + "."

def manipulate_words(str_list,func):
    new_list = []
    
    for word in str_list:
        new_list.append(func(word))
    return new_list

a = ["won't", "yOu", "CoMe", "sEE", "About", "me", 
              "i'll be alone", "danC ing", "you know it baby",
    "tell me", "your troubles and doubts", "giving me everything",
    "inside", "and", "out", "da - da"]

manipulate_words(a,punctuate)

["won't.",
 'yOu.',
 'CoMe.',
 'sEE.',
 'About.',
 'me.',
 "i'll be alone.",
 'danC ing.',
 'you know it baby.',
 'tell me.',
 'your troubles and doubts.',
 'giving me everything.',
 'inside.',
 'and.',
 'out.',
 'da - da.']

### 2.4 More unpacking

In [35]:

# Your code here
# cool stuff - you can make a variable stretch across everything that isn't defined by adding * behind
w, x, *y, z = np.array([1, 2, 3, 4, 5])
print(w, x, y, z)

# Ignore something entirely with *_
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 2 [3, 4] 5
1 5


## Exercise 1 :  A better calculator I

In [38]:
#dum dum dum dadada dadada DADADA dadada dadada
#boss music plays
import numpy as np

def add(x, y):
    result = x + y
    print(result)
    return result

def subtract(x, y):
    result = x - y
    print(result)
    return result

def multiply(x, y):
    result = x * y
    print(result)
    return result

def divide(x, y):
    assert 0 not in y, f"{x} cannot be divided by {y}! Returning null value"
    
    result = x/y
    print(result)
    return result

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x, y)
subtract(x, y)
multiply(x, y)
divide(x, y)



[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 2 :  A better calculator II

In [43]:
import numpy as np

def add(x, y):
    result = x + y
    print(result)
    return result

def subtract(x, y):
    result = x - y
    print(result)
    return result

def multiply(x, y):
    result = x * y
    print(result)
    return result

def divide(x, y):
    result = 0
    
    try:
        result = x/y
    except ZeroDivisionError: #this doesn't work for numpy arrays because they handle division by zero internally and just... don't throw exceptions?
        print(f"{x} cannot be divided by {y}! Returning null value")
        return None
    
    print(result)
    return result

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x, y)
subtract(x, y)
multiply(x, y)
divide(x, y)

divide(5,0) #sample case

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
5 cannot be divided by 0! Returning null value
