<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [32]:
# important learning point!!!! you can return multiple variables and do multiple assignment
# is this also unpacking?

import numpy as np

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

In [3]:
let = "let"

def set_let(net):
    let = net

set_let("get")

### 1.3 Anonymous functions

In [14]:
import random

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

i = random.randrange(2)

sorted(numbers, key=lambda x: x[i])  

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [15]:
print('I', 'am', 'Batman!') #basic
print('I', 'am', 'Batman!', sep='---') #looks cool
print('I', 'am', 'Batman!', end="") #this stops newline so you can just join together multiple strings if you don't want to do formatting

I am Batman!
I---am---Batman!
I am Batman!

## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [ ]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

If the name is <code>"Batman"</code>, the function immediately ends there and does not return <code>f"Hello {name}!"</code>. 

This works because this function returns something, which immediately ends the function and does not process anything after that.

## Exercise 2 :  Calculator functions

In [38]:
def add(x, y):
    result = x + y
    print(result)
    return result

def subtract(x, y):
    result = x - y
    print(result)
    return result

def multiply(x, y):
    result = x * y
    print(result)
    return result

def divide(x, y):
    result = 0
    
    if 0 not in y:
        result = x / y
    else:
        print(f"{x} cannot be divided by {y}! Returning null value")
        return None
    
    print(result)
    return result

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x, y)
subtract(x, y)
multiply(x, y)
divide(x, y)

[100 100 100 100 100   0]
[-28 -32 -12  52 -46   0]
[2304 2244 2464 1824 1971    0]
[36 34 44 76 27  0] cannot be divided by [64 66 56 24 73  0]! Returning null value


## Exercise 3 :  max_info() with NumPy

In [34]:
numbers = np.array([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])

print("Maximum Number: ",end="")
print(numbers.max())
print("Index of Maximum Number: ",end="")
print(numbers.argmax())

Maximum Number: 83
Index of Maximum Number: 2
